builds:
  -
    env:
      - CGO_ENABLED=1
    binary: commento
    goos:
      - linux
    goarch:
      - amd64
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: tar.gz
  files:
    - ./assets/js/**
    - ./assets/style/**
    - ./assets/vendor/**
